host: 0.0.0.0

sass:
  style: compressed

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      img: /assets/img/og.png
      description: Designer & Front end Developer. Working with large online platforms as well as campaign websites.
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /cases/:title