host: 0.0.0.0

sass:
  style: compressed

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      og:
        img: /assets/img/og.png
        description: Multidisciplinary designer who codes. Working with large online platforms as well as tasteful campaign websites. Currently lead product designer & creative developer at Dutch Railways (NS).
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /cases/:title